name: Test the project

on:
  schedule:
    - cron: '0 */12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      mail:
        description: 'Choose the mail provider to generate license'
        required: true
        type: choice
        options:
        - 1secmail
        - guerrillamail
        - developermail
        - mailticking
        - fakemail
        - inboxes
        - incognitomail
        - emailfake
        default: fakemail
      keys:
        description: 'Number of keys to be generated'
        required: true
        type: number
        default: 3
jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      URL: ${{ secrets.URL }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: 'Generate key'
        run: |
          EMAIL_API="${{ github.event.inputs.mail }}"
          KEY=${{ github.event.inputs.keys }}
          if [ -z "$EMAIL_API" ]; then
            EMAIL_API="emailfake"
          fi
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git clone --depth 1 https://github.com/pouet-pouet/etkg.git
          cd etkg
          # Setup env
          sudo apt update
          sudo apt install -y python3-pip python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          echo "Test results:" >> $GITHUB_STEP_SUMMARY
          if [[ ${KEY} != 0 ]]
          then
          for ((attempt=1;attempt<=${KEY};++attempt))
          do
          python3 main.py --auto-detect-browser --key --email-api ${EMAIL_API} --skip-update-check --no-logo --disable-progress-bar --disable-logging
          done
          echo -e "\nKeys generated:" >> $GITHUB_STEP_SUMMARY
          cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY
          fi
          echo 
          KEYS=$(cat ./*KEYS.txt)
          curl -X POST $URL \
            --header "Authorization: Bearer $API_TOKEN" \
            --data-urlencode "cles=$KEYS"
          cd ${{ github.workspace }}
          sudo rm -r etkg
